# SPDX-FileCopyrightText: 2026 The AIDA Core Authors
# SPDX-License-Identifier: MPL-2.0

"""Decision log primitives for the knowledge curator (#144).

Persists the curator's verdicts on candidate URLs across two files:

  * ``decisions.json`` — compact, structured audit log (source of truth)
  * ``decisions.md`` — generated, human-browseable summary of the JSON

The CONSISTENCY INVARIANT: these two files are written atomically as a
pair. Callers go through :func:`write_decisions`, which writes the
JSON and regenerates the Markdown in one call. There is no exported
function that writes one without the other.

The skill-side counterpart (``knowledge-curator``'s SKILL.md) carries
a matching policy line so the LLM-orchestrated workflow does not try
to hand-edit either file via Edit/Write tools.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

DECISIONS_JSON_FILENAME = "decisions.json"
DECISIONS_MD_FILENAME = "decisions.md"

SCHEMA_VERSION = "1.0.0"

# Two-line generated-file banner that lands at the top of every
# regenerated decisions.md. Mirrors how AIDA already signals generated
# files (configure.py / agent-manager output).
_GENERATED_BANNER = (
    "<!-- GENERATED by /aida knowledge curate — do not edit by hand -->\n"
    "<!-- Edit decisions.json (via /aida knowledge review) "
    "to change decisions -->\n"
)

DecisionStatus = Literal["pending", "in-use", "rejected"]
DecidedBy = Literal["llm", "human"]


@dataclass
class Decision:
    """One curator verdict on one candidate URL.

    All fields except ``url`` and ``status`` are optional and default
    appropriately for a fresh ``pending`` entry the spider writes.
    """

    url: str
    status: DecisionStatus
    decided_at: Optional[str] = None
    decided_by: Optional[DecidedBy] = None
    locked: bool = False
    reason: Optional[str] = None
    informs: List[str] = field(default_factory=list)
    discovered_at: Optional[str] = None
    source_root: Optional[str] = None
    last_synced: Optional[str] = None
    last_etag: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON-serializable dict, omitting None / empty defaults
        for compactness."""
        raw = asdict(self)
        out: Dict[str, Any] = {}
        for key, value in raw.items():
            if value is None:
                continue
            if key == "informs" and not value:
                continue
            if key == "locked" and value is False:
                continue
            out[key] = value
        return out


def now_iso() -> str:
    """UTC ISO-8601 timestamp at second resolution (matches #143 cache
    timestamps so logs interleave cleanly)."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _decisions_json_path(directory: Path) -> Path:
    return directory / DECISIONS_JSON_FILENAME


def _decisions_md_path(directory: Path) -> Path:
    return directory / DECISIONS_MD_FILENAME


def read_decisions(directory: Path) -> List[Decision]:
    """Load decisions from ``decisions.json``. Returns ``[]`` if the
    file is missing — that's the legitimate "no decisions yet" state.

    Raises ``ValueError`` if the file exists but is unreadable or has
    a wrong schema_version (caller decides whether to refuse the
    operation or attempt migration).
    """
    path = _decisions_json_path(directory)
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"decisions.json at {path} is not valid JSON: {exc}"
        ) from exc
    if not isinstance(data, dict):
        raise ValueError(
            f"decisions.json at {path} must be a JSON object."
        )
    version = data.get("version")
    if version is not None and version != SCHEMA_VERSION:
        raise ValueError(
            f"decisions.json at {path} declares version={version!r}; "
            f"this build understands {SCHEMA_VERSION!r}."
        )
    raw_entries = data.get("decisions", [])
    if not isinstance(raw_entries, list):
        raise ValueError(
            f"decisions.json at {path} `decisions` must be a list."
        )
    return [_decision_from_dict(entry) for entry in raw_entries]


def _decision_from_dict(raw: Dict[str, Any]) -> Decision:
    if not isinstance(raw, dict):
        raise ValueError(f"Decision entries must be objects, got {raw!r}.")
    url = raw.get("url")
    status = raw.get("status")
    if not isinstance(url, str) or not url:
        raise ValueError(f"Decision is missing url: {raw!r}.")
    if status not in ("pending", "in-use", "rejected"):
        raise ValueError(
            f"Decision {url!r} has invalid status {status!r}; "
            "must be one of pending / in-use / rejected."
        )
    return Decision(
        url=url,
        status=status,
        decided_at=raw.get("decided_at"),
        decided_by=raw.get("decided_by"),
        locked=bool(raw.get("locked", False)),
        reason=raw.get("reason"),
        informs=list(raw.get("informs", [])),
        discovered_at=raw.get("discovered_at"),
        source_root=raw.get("source_root"),
        last_synced=raw.get("last_synced"),
        last_etag=raw.get("last_etag"),
    )


def write_decisions(directory: Path, decisions: List[Decision]) -> None:
    """Atomically persist ``decisions`` to disk as the JSON+MD pair.

    This is the ONLY supported write path. Callers should never write
    either file directly — see the policy line in
    ``skills/knowledge-curator/SKILL.md`` for the LLM-side mirror of
    this invariant.

    The JSON write goes to a temp file first then replaces the live
    file, so a crash between the JSON and MD write doesn't leave the
    JSON corrupted. (The MD file is regenerated; partial MD is
    self-healing on the next call.)
    """
    directory.mkdir(parents=True, exist_ok=True)
    sorted_decisions = sorted(decisions, key=lambda d: d.url)
    _write_decisions_json(directory, sorted_decisions)
    _regenerate_decisions_md(directory, sorted_decisions)


def _write_decisions_json(
    directory: Path, decisions: List[Decision]
) -> None:
    path = _decisions_json_path(directory)
    tmp = path.with_suffix(path.suffix + ".tmp")
    payload = {
        "version": SCHEMA_VERSION,
        "decisions": [d.to_dict() for d in decisions],
    }
    tmp.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    tmp.replace(path)


def _regenerate_decisions_md(
    directory: Path, decisions: List[Decision]
) -> None:
    """Render decisions.md from the JSON state.

    Plain-dump format for Slice 1 — sections grouped by status, with
    one entry per URL carrying its metadata line and reason prose if
    present. Slice 2 may invest in richer formatting.
    """
    in_use = [d for d in decisions if d.status == "in-use"]
    rejected = [d for d in decisions if d.status == "rejected"]
    pending = [d for d in decisions if d.status == "pending"]

    out = [_GENERATED_BANNER, "\n# Curator Decisions\n"]

    out.append("\n## In-use\n")
    if in_use:
        for d in in_use:
            out.append(_render_decision(d))
    else:
        out.append("\n*No in-use decisions.*\n")

    out.append("\n## Rejected\n")
    if rejected:
        for d in rejected:
            out.append(_render_decision(d))
    else:
        out.append("\n*No rejected decisions.*\n")

    out.append("\n## Pending\n")
    if pending:
        for d in pending:
            out.append(_render_decision(d))
    else:
        out.append("\n*No pending decisions.*\n")

    _decisions_md_path(directory).write_text(
        "".join(out), encoding="utf-8"
    )


def _render_decision(d: Decision) -> str:
    lines = [f"\n### {d.url}\n"]
    meta_bits: List[str] = []
    if d.decided_at:
        meta_bits.append(f"Decided {d.decided_at}")
    elif d.discovered_at:
        meta_bits.append(f"Discovered {d.discovered_at}")
    if d.decided_by:
        meta_bits.append(f"by {d.decided_by}")
    if d.locked:
        meta_bits.append("**locked**")
    if d.informs:
        meta_bits.append(f"Informs: {', '.join(d.informs)}")
    if d.source_root:
        meta_bits.append(f"Source root: {d.source_root}")
    if meta_bits:
        lines.append(f"\n*{' · '.join(meta_bits)}*\n")
    if d.reason:
        lines.append(f"\n{d.reason}\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------


def find_by_url(
    decisions: List[Decision], url: str
) -> Optional[Decision]:
    """Return the existing decision for ``url``, or None."""
    for d in decisions:
        if d.url == url:
            return d
    return None


def upsert_decision(
    decisions: List[Decision], decision: Decision
) -> List[Decision]:
    """Return ``decisions`` with ``decision`` either appended (new URL)
    or replacing the existing entry for the same URL.

    Pure function; does not mutate the input list. Caller is expected
    to pass the result to :func:`write_decisions` to persist.
    """
    out: List[Decision] = []
    replaced = False
    for d in decisions:
        if d.url == decision.url:
            out.append(decision)
            replaced = True
        else:
            out.append(d)
    if not replaced:
        out.append(decision)
    return out
